services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mount the backend code for development
    networks:
      - mynetwork
    container_name: backend_service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the frontend code for development
    networks:
      - mynetwork
    container_name: frontend_service

networks:
  mynetwork: